version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - shopapp-network

  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shopapp-network

  ilucky-app:
    image: ilucky-spring
    container_name: ilucky-spring-container
    build: .
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/shop
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: my-redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8085:8085"
    networks:
      - shopapp-network

networks:
  shopapp-network:
    driver: bridge
