version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - shopapp-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shopapp-network
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - shopapp-network

#  ilucky-app:
#    build: .
#    container_name: ilucky-spring-container
#    depends_on:
#      - db
#      - redis
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/shop
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_REDIS_HOST: my-redis
#      SPRING_REDIS_PORT: 6379
#    ports:
#      - "8086:8085"
#      - "5005:5005"   # Cổng debug
#    networks:
#      - shopapp-network
#    command: >
#      java
#      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#      -jar app.jar

networks:
  shopapp-network:
    driver: bridge
