spring:
  application:
    name: ilucky

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/shop
    username: admin
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      use-redis-cache: true
      host: my-redis
      port: 6379

server:
  port: 8085
  servlet:
    session:
      timeout: 300

logging:
  level:
    root: INFO
    burundi.ilucky.service.ProductRedisService: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 8KYWNMKS
    secretKey: Y3E4R2DW4L0JZVJTPI6O4UHHY23PSI7C
    returnUrl: http://localhost:8085/api/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other